/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as DoacaoRouteImport } from './routes/doacao'
import { Route as InvisibleAcademyRouteImport } from './routes/invisible-academy'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as ProjetoEloRouteImport } from './routes/projeto-elo'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as SalaoRouteImport } from './routes/salao'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SolHairClosetRouteImport } from './routes/sol-hair-closet'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as ApiAcademyRouteImport } from './routes/api.academy'
import { Route as ApiAuthRouteImport } from './routes/api.auth'
import { Route as ApiCmsContentRouteImport } from './routes/api.cms-content'
import { Route as ApiDonationRouteImport } from './routes/api.donation'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiStoreRouteImport } from './routes/api.store'
import { Route as ApiStoreCustomerRouteImport } from './routes/api.store-customer'
import { Route as DoacaoRetornoRouteImport } from './routes/doacao.retorno'
import { Route as InvisibleAcademyIndexRouteImport } from './routes/invisible-academy.index'
import { Route as InvisibleAcademyAlunoRouteImport } from './routes/invisible-academy.aluno'
import { Route as SolHairClosetIndexRouteImport } from './routes/sol-hair-closet.index'
import { Route as SolHairClosetBuscaRouteImport } from './routes/sol-hair-closet.busca'
import { Route as SolHairClosetContaRouteImport } from './routes/sol-hair-closet.conta'
import { Route as SolHairClosetFavoritosRouteImport } from './routes/sol-hair-closet.favoritos'
import { Route as SolHairClosetPedidoRouteImport } from './routes/sol-hair-closet.pedido'
import { Route as SolHairClosetPedidosRouteImport } from './routes/sol-hair-closet.pedidos'
import { Route as SolHairClosetProdutosRouteImport } from './routes/sol-hair-closet.produtos'
import { Route as ApiAdminAcademyRouteImport } from './routes/api.admin.academy'
import { Route as ApiAdminCmsRouteImport } from './routes/api.admin.cms'
import { Route as ApiAdminDataRouteImport } from './routes/api.admin.data'
import { Route as ApiAdminEloRouteImport } from './routes/api.admin.elo'
import { Route as ApiAdminMediaRouteImport } from './routes/api.admin.media'
import { Route as ApiAdminNotificationsRouteImport } from './routes/api.admin.notifications'
import { Route as ApiAdminStoreRouteImport } from './routes/api.admin.store'
import { Route as ApiAdminSummaryRouteImport } from './routes/api.admin.summary'
import { Route as ApiAdminUsersRouteImport } from './routes/api.admin.users'
import { Route as ApiWebhookSumupRouteImport } from './routes/api.webhook.sumup'
import { Route as SolHairClosetCategoriaSlugRouteImport } from './routes/sol-hair-closet.categoria.$slug'
import { Route as SolHairClosetColecaoSlugRouteImport } from './routes/sol-hair-closet.colecao.$slug'
import { Route as SolHairClosetProdutoSlugRouteImport } from './routes/sol-hair-closet.produto.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const DoacaoRoute = DoacaoRouteImport.update({
  id: '/doacao',
  path: '/doacao',
  getParentRoute: () => rootRouteImport,
} as any)
const InvisibleAcademyRoute = InvisibleAcademyRouteImport.update({
  id: '/invisible-academy',
  path: '/invisible-academy',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetoEloRoute = ProjetoEloRouteImport.update({
  id: '/projeto-elo',
  path: '/projeto-elo',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaoRoute = SalaoRouteImport.update({
  id: '/salao',
  path: '/salao',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SolHairClosetRoute = SolHairClosetRouteImport.update({
  id: '/sol-hair-closet',
  path: '/sol-hair-closet',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAcademyRoute = ApiAcademyRouteImport.update({
  id: '/api/academy',
  path: '/api/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCmsContentRoute = ApiCmsContentRouteImport.update({
  id: '/api/cms-content',
  path: '/api/cms-content',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDonationRoute = ApiDonationRouteImport.update({
  id: '/api/donation',
  path: '/api/donation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoreRoute = ApiStoreRouteImport.update({
  id: '/api/store',
  path: '/api/store',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoreCustomerRoute = ApiStoreCustomerRouteImport.update({
  id: '/api/store-customer',
  path: '/api/store-customer',
  getParentRoute: () => rootRouteImport,
} as any)
const DoacaoRetornoRoute = DoacaoRetornoRouteImport.update({
  id: '/retorno',
  path: '/retorno',
  getParentRoute: () => DoacaoRoute,
} as any)
const InvisibleAcademyIndexRoute = InvisibleAcademyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InvisibleAcademyRoute,
} as any)
const InvisibleAcademyAlunoRoute = InvisibleAcademyAlunoRouteImport.update({
  id: '/aluno',
  path: '/aluno',
  getParentRoute: () => InvisibleAcademyRoute,
} as any)
const SolHairClosetIndexRoute = SolHairClosetIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SolHairClosetRoute,
} as any)
const SolHairClosetBuscaRoute = SolHairClosetBuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => SolHairClosetRoute,
} as any)
const SolHairClosetContaRoute = SolHairClosetContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => SolHairClosetRoute,
} as any)
const SolHairClosetFavoritosRoute = SolHairClosetFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => SolHairClosetRoute,
} as any)
const SolHairClosetPedidoRoute = SolHairClosetPedidoRouteImport.update({
  id: '/pedido',
  path: '/pedido',
  getParentRoute: () => SolHairClosetRoute,
} as any)
const SolHairClosetPedidosRoute = SolHairClosetPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => SolHairClosetRoute,
} as any)
const SolHairClosetProdutosRoute = SolHairClosetProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => SolHairClosetRoute,
} as any)
const ApiAdminAcademyRoute = ApiAdminAcademyRouteImport.update({
  id: '/api/admin/academy',
  path: '/api/admin/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCmsRoute = ApiAdminCmsRouteImport.update({
  id: '/api/admin/cms',
  path: '/api/admin/cms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDataRoute = ApiAdminDataRouteImport.update({
  id: '/api/admin/data',
  path: '/api/admin/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminEloRoute = ApiAdminEloRouteImport.update({
  id: '/api/admin/elo',
  path: '/api/admin/elo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMediaRoute = ApiAdminMediaRouteImport.update({
  id: '/api/admin/media',
  path: '/api/admin/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminNotificationsRoute = ApiAdminNotificationsRouteImport.update({
  id: '/api/admin/notifications',
  path: '/api/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStoreRoute = ApiAdminStoreRouteImport.update({
  id: '/api/admin/store',
  path: '/api/admin/store',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSummaryRoute = ApiAdminSummaryRouteImport.update({
  id: '/api/admin/summary',
  path: '/api/admin/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookSumupRoute = ApiWebhookSumupRouteImport.update({
  id: '/api/webhook/sumup',
  path: '/api/webhook/sumup',
  getParentRoute: () => rootRouteImport,
} as any)
const SolHairClosetCategoriaSlugRoute =
  SolHairClosetCategoriaSlugRouteImport.update({
    id: '/categoria/$slug',
    path: '/categoria/$slug',
    getParentRoute: () => SolHairClosetRoute,
  } as any)
const SolHairClosetColecaoSlugRoute =
  SolHairClosetColecaoSlugRouteImport.update({
    id: '/colecao/$slug',
    path: '/colecao/$slug',
    getParentRoute: () => SolHairClosetRoute,
  } as any)
const SolHairClosetProdutoSlugRoute =
  SolHairClosetProdutoSlugRouteImport.update({
    id: '/produto/$slug',
    path: '/produto/$slug',
    getParentRoute: () => SolHairClosetRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contato': typeof ContatoRoute
  '/doacao': typeof DoacaoRouteWithChildren
  '/invisible-academy': typeof InvisibleAcademyRouteWithChildren
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/projeto-elo': typeof ProjetoEloRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/salao': typeof SalaoRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/sol-hair-closet': typeof SolHairClosetRouteWithChildren
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/api/academy': typeof ApiAcademyRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/cms-content': typeof ApiCmsContentRoute
  '/api/donation': typeof ApiDonationRoute
  '/api/health': typeof ApiHealthRoute
  '/api/store': typeof ApiStoreRoute
  '/api/store-customer': typeof ApiStoreCustomerRoute
  '/doacao/retorno': typeof DoacaoRetornoRoute
  '/invisible-academy/aluno': typeof InvisibleAcademyAlunoRoute
  '/sol-hair-closet/busca': typeof SolHairClosetBuscaRoute
  '/sol-hair-closet/conta': typeof SolHairClosetContaRoute
  '/sol-hair-closet/favoritos': typeof SolHairClosetFavoritosRoute
  '/sol-hair-closet/pedido': typeof SolHairClosetPedidoRoute
  '/sol-hair-closet/pedidos': typeof SolHairClosetPedidosRoute
  '/sol-hair-closet/produtos': typeof SolHairClosetProdutosRoute
  '/invisible-academy/': typeof InvisibleAcademyIndexRoute
  '/sol-hair-closet/': typeof SolHairClosetIndexRoute
  '/api/admin/academy': typeof ApiAdminAcademyRoute
  '/api/admin/cms': typeof ApiAdminCmsRoute
  '/api/admin/data': typeof ApiAdminDataRoute
  '/api/admin/elo': typeof ApiAdminEloRoute
  '/api/admin/media': typeof ApiAdminMediaRoute
  '/api/admin/notifications': typeof ApiAdminNotificationsRoute
  '/api/admin/store': typeof ApiAdminStoreRoute
  '/api/admin/summary': typeof ApiAdminSummaryRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/webhook/sumup': typeof ApiWebhookSumupRoute
  '/sol-hair-closet/categoria/$slug': typeof SolHairClosetCategoriaSlugRoute
  '/sol-hair-closet/colecao/$slug': typeof SolHairClosetColecaoSlugRoute
  '/sol-hair-closet/produto/$slug': typeof SolHairClosetProdutoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contato': typeof ContatoRoute
  '/doacao': typeof DoacaoRouteWithChildren
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/projeto-elo': typeof ProjetoEloRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/salao': typeof SalaoRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/api/academy': typeof ApiAcademyRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/cms-content': typeof ApiCmsContentRoute
  '/api/donation': typeof ApiDonationRoute
  '/api/health': typeof ApiHealthRoute
  '/api/store': typeof ApiStoreRoute
  '/api/store-customer': typeof ApiStoreCustomerRoute
  '/doacao/retorno': typeof DoacaoRetornoRoute
  '/invisible-academy/aluno': typeof InvisibleAcademyAlunoRoute
  '/sol-hair-closet/busca': typeof SolHairClosetBuscaRoute
  '/sol-hair-closet/conta': typeof SolHairClosetContaRoute
  '/sol-hair-closet/favoritos': typeof SolHairClosetFavoritosRoute
  '/sol-hair-closet/pedido': typeof SolHairClosetPedidoRoute
  '/sol-hair-closet/pedidos': typeof SolHairClosetPedidosRoute
  '/sol-hair-closet/produtos': typeof SolHairClosetProdutosRoute
  '/invisible-academy': typeof InvisibleAcademyIndexRoute
  '/sol-hair-closet': typeof SolHairClosetIndexRoute
  '/api/admin/academy': typeof ApiAdminAcademyRoute
  '/api/admin/cms': typeof ApiAdminCmsRoute
  '/api/admin/data': typeof ApiAdminDataRoute
  '/api/admin/elo': typeof ApiAdminEloRoute
  '/api/admin/media': typeof ApiAdminMediaRoute
  '/api/admin/notifications': typeof ApiAdminNotificationsRoute
  '/api/admin/store': typeof ApiAdminStoreRoute
  '/api/admin/summary': typeof ApiAdminSummaryRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/webhook/sumup': typeof ApiWebhookSumupRoute
  '/sol-hair-closet/categoria/$slug': typeof SolHairClosetCategoriaSlugRoute
  '/sol-hair-closet/colecao/$slug': typeof SolHairClosetColecaoSlugRoute
  '/sol-hair-closet/produto/$slug': typeof SolHairClosetProdutoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contato': typeof ContatoRoute
  '/doacao': typeof DoacaoRouteWithChildren
  '/invisible-academy': typeof InvisibleAcademyRouteWithChildren
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/projeto-elo': typeof ProjetoEloRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/salao': typeof SalaoRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/sol-hair-closet': typeof SolHairClosetRouteWithChildren
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/api/academy': typeof ApiAcademyRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/cms-content': typeof ApiCmsContentRoute
  '/api/donation': typeof ApiDonationRoute
  '/api/health': typeof ApiHealthRoute
  '/api/store': typeof ApiStoreRoute
  '/api/store-customer': typeof ApiStoreCustomerRoute
  '/doacao/retorno': typeof DoacaoRetornoRoute
  '/invisible-academy/aluno': typeof InvisibleAcademyAlunoRoute
  '/sol-hair-closet/busca': typeof SolHairClosetBuscaRoute
  '/sol-hair-closet/conta': typeof SolHairClosetContaRoute
  '/sol-hair-closet/favoritos': typeof SolHairClosetFavoritosRoute
  '/sol-hair-closet/pedido': typeof SolHairClosetPedidoRoute
  '/sol-hair-closet/pedidos': typeof SolHairClosetPedidosRoute
  '/sol-hair-closet/produtos': typeof SolHairClosetProdutosRoute
  '/invisible-academy/': typeof InvisibleAcademyIndexRoute
  '/sol-hair-closet/': typeof SolHairClosetIndexRoute
  '/api/admin/academy': typeof ApiAdminAcademyRoute
  '/api/admin/cms': typeof ApiAdminCmsRoute
  '/api/admin/data': typeof ApiAdminDataRoute
  '/api/admin/elo': typeof ApiAdminEloRoute
  '/api/admin/media': typeof ApiAdminMediaRoute
  '/api/admin/notifications': typeof ApiAdminNotificationsRoute
  '/api/admin/store': typeof ApiAdminStoreRoute
  '/api/admin/summary': typeof ApiAdminSummaryRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/webhook/sumup': typeof ApiWebhookSumupRoute
  '/sol-hair-closet/categoria/$slug': typeof SolHairClosetCategoriaSlugRoute
  '/sol-hair-closet/colecao/$slug': typeof SolHairClosetColecaoSlugRoute
  '/sol-hair-closet/produto/$slug': typeof SolHairClosetProdutoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contato'
    | '/doacao'
    | '/invisible-academy'
    | '/politica-de-privacidade'
    | '/projeto-elo'
    | '/redefinir-senha'
    | '/salao'
    | '/servicos'
    | '/sobre'
    | '/sol-hair-closet'
    | '/termos-de-uso'
    | '/api/academy'
    | '/api/auth'
    | '/api/cms-content'
    | '/api/donation'
    | '/api/health'
    | '/api/store'
    | '/api/store-customer'
    | '/doacao/retorno'
    | '/invisible-academy/aluno'
    | '/sol-hair-closet/busca'
    | '/sol-hair-closet/conta'
    | '/sol-hair-closet/favoritos'
    | '/sol-hair-closet/pedido'
    | '/sol-hair-closet/pedidos'
    | '/sol-hair-closet/produtos'
    | '/invisible-academy/'
    | '/sol-hair-closet/'
    | '/api/admin/academy'
    | '/api/admin/cms'
    | '/api/admin/data'
    | '/api/admin/elo'
    | '/api/admin/media'
    | '/api/admin/notifications'
    | '/api/admin/store'
    | '/api/admin/summary'
    | '/api/admin/users'
    | '/api/webhook/sumup'
    | '/sol-hair-closet/categoria/$slug'
    | '/sol-hair-closet/colecao/$slug'
    | '/sol-hair-closet/produto/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/contato'
    | '/doacao'
    | '/politica-de-privacidade'
    | '/projeto-elo'
    | '/redefinir-senha'
    | '/salao'
    | '/servicos'
    | '/sobre'
    | '/termos-de-uso'
    | '/api/academy'
    | '/api/auth'
    | '/api/cms-content'
    | '/api/donation'
    | '/api/health'
    | '/api/store'
    | '/api/store-customer'
    | '/doacao/retorno'
    | '/invisible-academy/aluno'
    | '/sol-hair-closet/busca'
    | '/sol-hair-closet/conta'
    | '/sol-hair-closet/favoritos'
    | '/sol-hair-closet/pedido'
    | '/sol-hair-closet/pedidos'
    | '/sol-hair-closet/produtos'
    | '/invisible-academy'
    | '/sol-hair-closet'
    | '/api/admin/academy'
    | '/api/admin/cms'
    | '/api/admin/data'
    | '/api/admin/elo'
    | '/api/admin/media'
    | '/api/admin/notifications'
    | '/api/admin/store'
    | '/api/admin/summary'
    | '/api/admin/users'
    | '/api/webhook/sumup'
    | '/sol-hair-closet/categoria/$slug'
    | '/sol-hair-closet/colecao/$slug'
    | '/sol-hair-closet/produto/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contato'
    | '/doacao'
    | '/invisible-academy'
    | '/politica-de-privacidade'
    | '/projeto-elo'
    | '/redefinir-senha'
    | '/salao'
    | '/servicos'
    | '/sobre'
    | '/sol-hair-closet'
    | '/termos-de-uso'
    | '/api/academy'
    | '/api/auth'
    | '/api/cms-content'
    | '/api/donation'
    | '/api/health'
    | '/api/store'
    | '/api/store-customer'
    | '/doacao/retorno'
    | '/invisible-academy/aluno'
    | '/sol-hair-closet/busca'
    | '/sol-hair-closet/conta'
    | '/sol-hair-closet/favoritos'
    | '/sol-hair-closet/pedido'
    | '/sol-hair-closet/pedidos'
    | '/sol-hair-closet/produtos'
    | '/invisible-academy/'
    | '/sol-hair-closet/'
    | '/api/admin/academy'
    | '/api/admin/cms'
    | '/api/admin/data'
    | '/api/admin/elo'
    | '/api/admin/media'
    | '/api/admin/notifications'
    | '/api/admin/store'
    | '/api/admin/summary'
    | '/api/admin/users'
    | '/api/webhook/sumup'
    | '/sol-hair-closet/categoria/$slug'
    | '/sol-hair-closet/colecao/$slug'
    | '/sol-hair-closet/produto/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ContatoRoute: typeof ContatoRoute
  DoacaoRoute: typeof DoacaoRouteWithChildren
  InvisibleAcademyRoute: typeof InvisibleAcademyRouteWithChildren
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  ProjetoEloRoute: typeof ProjetoEloRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  SalaoRoute: typeof SalaoRoute
  ServicosRoute: typeof ServicosRoute
  SobreRoute: typeof SobreRoute
  SolHairClosetRoute: typeof SolHairClosetRouteWithChildren
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  ApiAcademyRoute: typeof ApiAcademyRoute
  ApiAuthRoute: typeof ApiAuthRoute
  ApiCmsContentRoute: typeof ApiCmsContentRoute
  ApiDonationRoute: typeof ApiDonationRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiStoreRoute: typeof ApiStoreRoute
  ApiStoreCustomerRoute: typeof ApiStoreCustomerRoute
  ApiAdminAcademyRoute: typeof ApiAdminAcademyRoute
  ApiAdminCmsRoute: typeof ApiAdminCmsRoute
  ApiAdminDataRoute: typeof ApiAdminDataRoute
  ApiAdminEloRoute: typeof ApiAdminEloRoute
  ApiAdminMediaRoute: typeof ApiAdminMediaRoute
  ApiAdminNotificationsRoute: typeof ApiAdminNotificationsRoute
  ApiAdminStoreRoute: typeof ApiAdminStoreRoute
  ApiAdminSummaryRoute: typeof ApiAdminSummaryRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiWebhookSumupRoute: typeof ApiWebhookSumupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doacao': {
      id: '/doacao'
      path: '/doacao'
      fullPath: '/doacao'
      preLoaderRoute: typeof DoacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invisible-academy': {
      id: '/invisible-academy'
      path: '/invisible-academy'
      fullPath: '/invisible-academy'
      preLoaderRoute: typeof InvisibleAcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projeto-elo': {
      id: '/projeto-elo'
      path: '/projeto-elo'
      fullPath: '/projeto-elo'
      preLoaderRoute: typeof ProjetoEloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salao': {
      id: '/salao'
      path: '/salao'
      fullPath: '/salao'
      preLoaderRoute: typeof SalaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sol-hair-closet': {
      id: '/sol-hair-closet'
      path: '/sol-hair-closet'
      fullPath: '/sol-hair-closet'
      preLoaderRoute: typeof SolHairClosetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/academy': {
      id: '/api/academy'
      path: '/api/academy'
      fullPath: '/api/academy'
      preLoaderRoute: typeof ApiAcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cms-content': {
      id: '/api/cms-content'
      path: '/api/cms-content'
      fullPath: '/api/cms-content'
      preLoaderRoute: typeof ApiCmsContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/donation': {
      id: '/api/donation'
      path: '/api/donation'
      fullPath: '/api/donation'
      preLoaderRoute: typeof ApiDonationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/store': {
      id: '/api/store'
      path: '/api/store'
      fullPath: '/api/store'
      preLoaderRoute: typeof ApiStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/store-customer': {
      id: '/api/store-customer'
      path: '/api/store-customer'
      fullPath: '/api/store-customer'
      preLoaderRoute: typeof ApiStoreCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doacao/retorno': {
      id: '/doacao/retorno'
      path: '/retorno'
      fullPath: '/doacao/retorno'
      preLoaderRoute: typeof DoacaoRetornoRouteImport
      parentRoute: typeof DoacaoRoute
    }
    '/invisible-academy/': {
      id: '/invisible-academy/'
      path: '/'
      fullPath: '/invisible-academy/'
      preLoaderRoute: typeof InvisibleAcademyIndexRouteImport
      parentRoute: typeof InvisibleAcademyRoute
    }
    '/invisible-academy/aluno': {
      id: '/invisible-academy/aluno'
      path: '/aluno'
      fullPath: '/invisible-academy/aluno'
      preLoaderRoute: typeof InvisibleAcademyAlunoRouteImport
      parentRoute: typeof InvisibleAcademyRoute
    }
    '/sol-hair-closet/': {
      id: '/sol-hair-closet/'
      path: '/'
      fullPath: '/sol-hair-closet/'
      preLoaderRoute: typeof SolHairClosetIndexRouteImport
      parentRoute: typeof SolHairClosetRoute
    }
    '/sol-hair-closet/busca': {
      id: '/sol-hair-closet/busca'
      path: '/busca'
      fullPath: '/sol-hair-closet/busca'
      preLoaderRoute: typeof SolHairClosetBuscaRouteImport
      parentRoute: typeof SolHairClosetRoute
    }
    '/sol-hair-closet/conta': {
      id: '/sol-hair-closet/conta'
      path: '/conta'
      fullPath: '/sol-hair-closet/conta'
      preLoaderRoute: typeof SolHairClosetContaRouteImport
      parentRoute: typeof SolHairClosetRoute
    }
    '/sol-hair-closet/favoritos': {
      id: '/sol-hair-closet/favoritos'
      path: '/favoritos'
      fullPath: '/sol-hair-closet/favoritos'
      preLoaderRoute: typeof SolHairClosetFavoritosRouteImport
      parentRoute: typeof SolHairClosetRoute
    }
    '/sol-hair-closet/pedido': {
      id: '/sol-hair-closet/pedido'
      path: '/pedido'
      fullPath: '/sol-hair-closet/pedido'
      preLoaderRoute: typeof SolHairClosetPedidoRouteImport
      parentRoute: typeof SolHairClosetRoute
    }
    '/sol-hair-closet/pedidos': {
      id: '/sol-hair-closet/pedidos'
      path: '/pedidos'
      fullPath: '/sol-hair-closet/pedidos'
      preLoaderRoute: typeof SolHairClosetPedidosRouteImport
      parentRoute: typeof SolHairClosetRoute
    }
    '/sol-hair-closet/produtos': {
      id: '/sol-hair-closet/produtos'
      path: '/produtos'
      fullPath: '/sol-hair-closet/produtos'
      preLoaderRoute: typeof SolHairClosetProdutosRouteImport
      parentRoute: typeof SolHairClosetRoute
    }
    '/api/admin/academy': {
      id: '/api/admin/academy'
      path: '/api/admin/academy'
      fullPath: '/api/admin/academy'
      preLoaderRoute: typeof ApiAdminAcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/cms': {
      id: '/api/admin/cms'
      path: '/api/admin/cms'
      fullPath: '/api/admin/cms'
      preLoaderRoute: typeof ApiAdminCmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/data': {
      id: '/api/admin/data'
      path: '/api/admin/data'
      fullPath: '/api/admin/data'
      preLoaderRoute: typeof ApiAdminDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/elo': {
      id: '/api/admin/elo'
      path: '/api/admin/elo'
      fullPath: '/api/admin/elo'
      preLoaderRoute: typeof ApiAdminEloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/media': {
      id: '/api/admin/media'
      path: '/api/admin/media'
      fullPath: '/api/admin/media'
      preLoaderRoute: typeof ApiAdminMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/notifications': {
      id: '/api/admin/notifications'
      path: '/api/admin/notifications'
      fullPath: '/api/admin/notifications'
      preLoaderRoute: typeof ApiAdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/store': {
      id: '/api/admin/store'
      path: '/api/admin/store'
      fullPath: '/api/admin/store'
      preLoaderRoute: typeof ApiAdminStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/summary': {
      id: '/api/admin/summary'
      path: '/api/admin/summary'
      fullPath: '/api/admin/summary'
      preLoaderRoute: typeof ApiAdminSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook/sumup': {
      id: '/api/webhook/sumup'
      path: '/api/webhook/sumup'
      fullPath: '/api/webhook/sumup'
      preLoaderRoute: typeof ApiWebhookSumupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sol-hair-closet/categoria/$slug': {
      id: '/sol-hair-closet/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/sol-hair-closet/categoria/$slug'
      preLoaderRoute: typeof SolHairClosetCategoriaSlugRouteImport
      parentRoute: typeof SolHairClosetRoute
    }
    '/sol-hair-closet/colecao/$slug': {
      id: '/sol-hair-closet/colecao/$slug'
      path: '/colecao/$slug'
      fullPath: '/sol-hair-closet/colecao/$slug'
      preLoaderRoute: typeof SolHairClosetColecaoSlugRouteImport
      parentRoute: typeof SolHairClosetRoute
    }
    '/sol-hair-closet/produto/$slug': {
      id: '/sol-hair-closet/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/sol-hair-closet/produto/$slug'
      preLoaderRoute: typeof SolHairClosetProdutoSlugRouteImport
      parentRoute: typeof SolHairClosetRoute
    }
  }
}

interface DoacaoRouteChildren {
  DoacaoRetornoRoute: typeof DoacaoRetornoRoute
}

const DoacaoRouteChildren: DoacaoRouteChildren = {
  DoacaoRetornoRoute: DoacaoRetornoRoute,
}

const DoacaoRouteWithChildren =
  DoacaoRoute._addFileChildren(DoacaoRouteChildren)

interface InvisibleAcademyRouteChildren {
  InvisibleAcademyAlunoRoute: typeof InvisibleAcademyAlunoRoute
  InvisibleAcademyIndexRoute: typeof InvisibleAcademyIndexRoute
}

const InvisibleAcademyRouteChildren: InvisibleAcademyRouteChildren = {
  InvisibleAcademyAlunoRoute: InvisibleAcademyAlunoRoute,
  InvisibleAcademyIndexRoute: InvisibleAcademyIndexRoute,
}

const InvisibleAcademyRouteWithChildren =
  InvisibleAcademyRoute._addFileChildren(InvisibleAcademyRouteChildren)

interface SolHairClosetRouteChildren {
  SolHairClosetBuscaRoute: typeof SolHairClosetBuscaRoute
  SolHairClosetContaRoute: typeof SolHairClosetContaRoute
  SolHairClosetFavoritosRoute: typeof SolHairClosetFavoritosRoute
  SolHairClosetPedidoRoute: typeof SolHairClosetPedidoRoute
  SolHairClosetPedidosRoute: typeof SolHairClosetPedidosRoute
  SolHairClosetProdutosRoute: typeof SolHairClosetProdutosRoute
  SolHairClosetIndexRoute: typeof SolHairClosetIndexRoute
  SolHairClosetCategoriaSlugRoute: typeof SolHairClosetCategoriaSlugRoute
  SolHairClosetColecaoSlugRoute: typeof SolHairClosetColecaoSlugRoute
  SolHairClosetProdutoSlugRoute: typeof SolHairClosetProdutoSlugRoute
}

const SolHairClosetRouteChildren: SolHairClosetRouteChildren = {
  SolHairClosetBuscaRoute: SolHairClosetBuscaRoute,
  SolHairClosetContaRoute: SolHairClosetContaRoute,
  SolHairClosetFavoritosRoute: SolHairClosetFavoritosRoute,
  SolHairClosetPedidoRoute: SolHairClosetPedidoRoute,
  SolHairClosetPedidosRoute: SolHairClosetPedidosRoute,
  SolHairClosetProdutosRoute: SolHairClosetProdutosRoute,
  SolHairClosetIndexRoute: SolHairClosetIndexRoute,
  SolHairClosetCategoriaSlugRoute: SolHairClosetCategoriaSlugRoute,
  SolHairClosetColecaoSlugRoute: SolHairClosetColecaoSlugRoute,
  SolHairClosetProdutoSlugRoute: SolHairClosetProdutoSlugRoute,
}

const SolHairClosetRouteWithChildren = SolHairClosetRoute._addFileChildren(
  SolHairClosetRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ContatoRoute: ContatoRoute,
  DoacaoRoute: DoacaoRouteWithChildren,
  InvisibleAcademyRoute: InvisibleAcademyRouteWithChildren,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  ProjetoEloRoute: ProjetoEloRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  SalaoRoute: SalaoRoute,
  ServicosRoute: ServicosRoute,
  SobreRoute: SobreRoute,
  SolHairClosetRoute: SolHairClosetRouteWithChildren,
  TermosDeUsoRoute: TermosDeUsoRoute,
  ApiAcademyRoute: ApiAcademyRoute,
  ApiAuthRoute: ApiAuthRoute,
  ApiCmsContentRoute: ApiCmsContentRoute,
  ApiDonationRoute: ApiDonationRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiStoreRoute: ApiStoreRoute,
  ApiStoreCustomerRoute: ApiStoreCustomerRoute,
  ApiAdminAcademyRoute: ApiAdminAcademyRoute,
  ApiAdminCmsRoute: ApiAdminCmsRoute,
  ApiAdminDataRoute: ApiAdminDataRoute,
  ApiAdminEloRoute: ApiAdminEloRoute,
  ApiAdminMediaRoute: ApiAdminMediaRoute,
  ApiAdminNotificationsRoute: ApiAdminNotificationsRoute,
  ApiAdminStoreRoute: ApiAdminStoreRoute,
  ApiAdminSummaryRoute: ApiAdminSummaryRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiWebhookSumupRoute: ApiWebhookSumupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
