/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvisibleAcademyRouteImport } from './routes/invisible-academy'
import { Route as ProjetoEloRouteImport } from './routes/projeto-elo'
import { Route as SolHairClosetRouteImport } from './routes/sol-hair-closet'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvisibleAcademyRoute = InvisibleAcademyRouteImport.update({
  id: '/invisible-academy',
  path: '/invisible-academy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetoEloRoute = ProjetoEloRouteImport.update({
  id: '/projeto-elo',
  path: '/projeto-elo',
  getParentRoute: () => rootRouteImport,
} as any)
const SolHairClosetRoute = SolHairClosetRouteImport.update({
  id: '/sol-hair-closet',
  path: '/sol-hair-closet',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invisible-academy': typeof InvisibleAcademyRoute
  '/projeto-elo': typeof ProjetoEloRoute
  '/sol-hair-closet': typeof SolHairClosetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invisible-academy': typeof InvisibleAcademyRoute
  '/projeto-elo': typeof ProjetoEloRoute
  '/sol-hair-closet': typeof SolHairClosetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/invisible-academy': typeof InvisibleAcademyRoute
  '/projeto-elo': typeof ProjetoEloRoute
  '/sol-hair-closet': typeof SolHairClosetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/invisible-academy' | '/projeto-elo' | '/sol-hair-closet'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/invisible-academy' | '/projeto-elo' | '/sol-hair-closet'
  id:
    | '__root__'
    | '/'
    | '/invisible-academy'
    | '/projeto-elo'
    | '/sol-hair-closet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InvisibleAcademyRoute: typeof InvisibleAcademyRoute
  ProjetoEloRoute: typeof ProjetoEloRoute
  SolHairClosetRoute: typeof SolHairClosetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invisible-academy': {
      id: '/invisible-academy'
      path: '/invisible-academy'
      fullPath: '/invisible-academy'
      preLoaderRoute: typeof InvisibleAcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projeto-elo': {
      id: '/projeto-elo'
      path: '/projeto-elo'
      fullPath: '/projeto-elo'
      preLoaderRoute: typeof ProjetoEloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sol-hair-closet': {
      id: '/sol-hair-closet'
      path: '/sol-hair-closet'
      fullPath: '/sol-hair-closet'
      preLoaderRoute: typeof SolHairClosetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InvisibleAcademyRoute: InvisibleAcademyRoute,
  ProjetoEloRoute: ProjetoEloRoute,
  SolHairClosetRoute: SolHairClosetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
