/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as InvisibleAcademyRouteImport } from './routes/invisible-academy'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as ProjetoEloRouteImport } from './routes/projeto-elo'
import { Route as SalaoRouteImport } from './routes/salao'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SolHairClosetRouteImport } from './routes/sol-hair-closet'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as ApiAuthRouteImport } from './routes/api.auth'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiAdminSummaryRouteImport } from './routes/api.admin.summary'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const InvisibleAcademyRoute = InvisibleAcademyRouteImport.update({
  id: '/invisible-academy',
  path: '/invisible-academy',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetoEloRoute = ProjetoEloRouteImport.update({
  id: '/projeto-elo',
  path: '/projeto-elo',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaoRoute = SalaoRouteImport.update({
  id: '/salao',
  path: '/salao',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SolHairClosetRoute = SolHairClosetRouteImport.update({
  id: '/sol-hair-closet',
  path: '/sol-hair-closet',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSummaryRoute = ApiAdminSummaryRouteImport.update({
  id: '/api/admin/summary',
  path: '/api/admin/summary',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contato': typeof ContatoRoute
  '/invisible-academy': typeof InvisibleAcademyRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/projeto-elo': typeof ProjetoEloRoute
  '/salao': typeof SalaoRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/sol-hair-closet': typeof SolHairClosetRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/health': typeof ApiHealthRoute
  '/api/admin/summary': typeof ApiAdminSummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contato': typeof ContatoRoute
  '/invisible-academy': typeof InvisibleAcademyRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/projeto-elo': typeof ProjetoEloRoute
  '/salao': typeof SalaoRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/sol-hair-closet': typeof SolHairClosetRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/health': typeof ApiHealthRoute
  '/api/admin/summary': typeof ApiAdminSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contato': typeof ContatoRoute
  '/invisible-academy': typeof InvisibleAcademyRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/projeto-elo': typeof ProjetoEloRoute
  '/salao': typeof SalaoRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/sol-hair-closet': typeof SolHairClosetRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/health': typeof ApiHealthRoute
  '/api/admin/summary': typeof ApiAdminSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contato'
    | '/invisible-academy'
    | '/politica-de-privacidade'
    | '/projeto-elo'
    | '/salao'
    | '/servicos'
    | '/sobre'
    | '/sol-hair-closet'
    | '/termos-de-uso'
    | '/api/auth'
    | '/api/health'
    | '/api/admin/summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/contato'
    | '/invisible-academy'
    | '/politica-de-privacidade'
    | '/projeto-elo'
    | '/salao'
    | '/servicos'
    | '/sobre'
    | '/sol-hair-closet'
    | '/termos-de-uso'
    | '/api/auth'
    | '/api/health'
    | '/api/admin/summary'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contato'
    | '/invisible-academy'
    | '/politica-de-privacidade'
    | '/projeto-elo'
    | '/salao'
    | '/servicos'
    | '/sobre'
    | '/sol-hair-closet'
    | '/termos-de-uso'
    | '/api/auth'
    | '/api/health'
    | '/api/admin/summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ContatoRoute: typeof ContatoRoute
  InvisibleAcademyRoute: typeof InvisibleAcademyRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  ProjetoEloRoute: typeof ProjetoEloRoute
  SalaoRoute: typeof SalaoRoute
  ServicosRoute: typeof ServicosRoute
  SobreRoute: typeof SobreRoute
  SolHairClosetRoute: typeof SolHairClosetRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  ApiAuthRoute: typeof ApiAuthRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAdminSummaryRoute: typeof ApiAdminSummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invisible-academy': {
      id: '/invisible-academy'
      path: '/invisible-academy'
      fullPath: '/invisible-academy'
      preLoaderRoute: typeof InvisibleAcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projeto-elo': {
      id: '/projeto-elo'
      path: '/projeto-elo'
      fullPath: '/projeto-elo'
      preLoaderRoute: typeof ProjetoEloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salao': {
      id: '/salao'
      path: '/salao'
      fullPath: '/salao'
      preLoaderRoute: typeof SalaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sol-hair-closet': {
      id: '/sol-hair-closet'
      path: '/sol-hair-closet'
      fullPath: '/sol-hair-closet'
      preLoaderRoute: typeof SolHairClosetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/summary': {
      id: '/api/admin/summary'
      path: '/api/admin/summary'
      fullPath: '/api/admin/summary'
      preLoaderRoute: typeof ApiAdminSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ContatoRoute: ContatoRoute,
  InvisibleAcademyRoute: InvisibleAcademyRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  ProjetoEloRoute: ProjetoEloRoute,
  SalaoRoute: SalaoRoute,
  ServicosRoute: ServicosRoute,
  SobreRoute: SobreRoute,
  SolHairClosetRoute: SolHairClosetRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  ApiAuthRoute: ApiAuthRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAdminSummaryRoute: ApiAdminSummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
